package mitm

import (
	"fmt"
	"go/format"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// CodegenOptions configures wire-constant generation from a
// Snapshot. PackageName is the Go package that will own the
// generated file (e.g. "codex" or "anthropic"). OutputDir is the
// directory the file lands in; default is
// `internal/adapter/<package>/`.
type CodegenOptions struct {
	PackageName string
	OutputDir   string
	UpstreamRef string // path to the reference.toml so the file can record provenance
}

// GenerateWireConstants writes wire_constants_gen.go for the given
// snapshot. The file declares constants the adapter's request_builder
// can import directly. The local `wire-snapshot-check` gate ensures
// the file stays in sync with the current user-local baseline.
//
// The generated file is gofmt'd before write so reviewing the diff
// surfaces real semantic changes rather than formatting churn.
func GenerateWireConstants(snap Snapshot, opts CodegenOptions) (string, error) {
	if opts.PackageName == "" {
		return "", fmt.Errorf("codegen: PackageName is required")
	}
	dir := opts.OutputDir
	if dir == "" {
		dir = filepath.Join("internal", "adapter", opts.PackageName)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		slog.Warn("mitm.codegen.mkdir_failed",
			"component", "mitm",
			"dir", dir,
			"package", opts.PackageName,
			"err", err,
		)
		return "", fmt.Errorf("codegen mkdir: %w", err)
	}

	body := buildWireConstantsSource(snap, opts)
	formatted, err := format.Source([]byte(body))
	if err != nil {
		slog.Warn("mitm.codegen.gofmt_failed",
			"component", "mitm",
			"package", opts.PackageName,
			"err", err,
		)
		return "", fmt.Errorf("codegen gofmt: %w\n%s", err, body)
	}
	out := filepath.Join(dir, "wire_constants_gen.go")
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		slog.Warn("mitm.codegen.write_failed",
			"component", "mitm",
			"path", out,
			"package", opts.PackageName,
			"err", err,
		)
		return "", fmt.Errorf("codegen write: %w", err)
	}
	return out, nil
}

func buildWireConstantsSource(snap Snapshot, opts CodegenOptions) string {
	var b strings.Builder
	b.WriteString("// Code generated by clyde mitm codegen. DO NOT EDIT.\n")
	b.WriteString("// Source: ")
	if opts.UpstreamRef != "" {
		b.WriteString(opts.UpstreamRef)
	} else {
		b.WriteString("(Snapshot)")
	}
	b.WriteString("\n// Captured: ")
	if snap.Upstream.CapturedAt != "" {
		b.WriteString(snap.Upstream.CapturedAt)
	} else {
		b.WriteString(currentTime().UTC().Format(time.RFC3339))
	}
	b.WriteString("\n//\n// Run `clyde mitm codegen --upstream ")
	b.WriteString(snap.Upstream.Name)
	b.WriteString(" <reference.toml>` to regenerate.\n\n")
	b.WriteString("package ")
	b.WriteString(opts.PackageName)
	b.WriteString("\n\n")

	b.WriteString("// Wire constants extracted from the captured reference.\n")
	b.WriteString("const (\n")
	emitConst(&b, "WireOriginator", snap.Constants.Originator)
	emitConst(&b, "WireOpenAIBeta", snap.Constants.OpenAIBeta)
	emitConst(&b, "WireUserAgent", snap.Constants.UserAgent)
	emitConst(&b, "WireBetaFeatures", snap.Constants.BetaFeatures)
	emitConst(&b, "WireStainlessPackageVersion", snap.Constants.StainlessPackageVersion)
	emitConst(&b, "WireUpstreamName", snap.Upstream.Name)
	emitConst(&b, "WireUpstreamVersion", snap.Upstream.Version)
	emitConst(&b, "WireBodyType", snap.Body.Type)
	b.WriteString(")\n")

	b.WriteString("\n// Sets observed in the captured reference. The adapter\n")
	b.WriteString("// can compare its request_builder output against these to\n")
	b.WriteString("// catch silent drift.\n")
	emitStringSlice(&b, "WireBodyFieldNames", snap.Body.FieldNames)
	emitStringSlice(&b, "WireIncludeKeys", snap.Body.IncludeKeys)
	emitStringSlice(&b, "WireToolKinds", snap.Body.ToolKinds)
	return b.String()
}

func emitConst(b *strings.Builder, name, value string) {
	if value == "" {
		fmt.Fprintf(b, "\t%s = \"\" // not observed in capture\n", name)
		return
	}
	fmt.Fprintf(b, "\t%s = %q\n", name, value)
}

func emitStringSlice(b *strings.Builder, name string, values []string) {
	if len(values) == 0 {
		fmt.Fprintf(b, "\nvar %s = []string{}\n", name)
		return
	}
	fmt.Fprintf(b, "\nvar %s = []string{\n", name)
	for _, v := range values {
		fmt.Fprintf(b, "\t%q,\n", v)
	}
	fmt.Fprintln(b, "}")
}
