package mitm

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GenerateWireFlavors writes wire_flavors_gen.go for the given v2
// snapshot. Each captured flavor becomes a typed WireFlavor value the
// adapter's request_builder can consume directly. The local
// `wire-snapshot-check` gate ensures the file stays in sync with the
// current user-local baseline.
//
// Compared to v1's GenerateWireConstants, v2 emits:
//   - one WireFlavor per observed caller flavor
//   - typed []WireHeader (no map[string]string) for type hygiene
//   - only "constant" classification headers as required values; "enum"
//     and "free" are surfaced as observed-value lists for diffing
//   - a Flavors slice the adapter can iterate to pick a flavor at runtime
//
// The generated file is gofmt'd before write so reviewing the diff
// surfaces real semantic changes rather than formatting churn.
func GenerateWireFlavors(snap SnapshotV2, opts CodegenOptions) (string, error) {
	if opts.PackageName == "" {
		return "", fmt.Errorf("codegen v2: PackageName is required")
	}
	dir := opts.OutputDir
	if dir == "" {
		dir = filepath.Join("internal", "adapter", opts.PackageName)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("codegen v2 mkdir: %w", err)
	}

	body := buildWireFlavorsSource(snap, opts)
	formatted, err := format.Source([]byte(body))
	if err != nil {
		return "", fmt.Errorf("codegen v2 gofmt: %w\n%s", err, body)
	}
	out := filepath.Join(dir, "wire_flavors_gen.go")
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		return "", fmt.Errorf("codegen v2 write: %w", err)
	}
	return out, nil
}

func buildWireFlavorsSource(snap SnapshotV2, opts CodegenOptions) string {
	var b strings.Builder
	b.WriteString("// Code generated by clyde mitm codegen. DO NOT EDIT.\n")
	b.WriteString("// Source: ")
	if opts.UpstreamRef != "" {
		b.WriteString(opts.UpstreamRef)
	} else {
		b.WriteString("(SnapshotV2)")
	}
	b.WriteString("\n// Captured: ")
	if snap.Upstream.CapturedAt != "" {
		b.WriteString(snap.Upstream.CapturedAt)
	} else {
		b.WriteString(time.Now().UTC().Format(time.RFC3339))
	}
	b.WriteString("\n// Upstream: ")
	b.WriteString(snap.Upstream.Name)
	fmt.Fprintf(&b, "\n// Flavors observed: %d", len(snap.Flavors))
	b.WriteString("\n//\n// Run `clyde mitm codegen --package ")
	b.WriteString(opts.PackageName)
	b.WriteString(" <reference.toml>` to regenerate.\n\n")
	b.WriteString("package ")
	b.WriteString(opts.PackageName)
	b.WriteString("\n\n")

	b.WriteString(`// WireHeader is one outbound HTTP header. Name is canonical-cased.
// Value is the literal value observed in the captured reference for
// "constant"-classified headers. For "enum" and "free" headers the
// generator surfaces a sample value; the adapter is responsible for
// computing the real value at runtime.
type WireHeader struct {
	Name           string
	Value          string
	Classification string // "constant" | "enum" | "free"
}

// WireFlavor is the captured wire shape for one caller flavor of an
// upstream. Fields are typed to satisfy strict type hygiene; no
// map[string]string or interface{} appears here.
type WireFlavor struct {
	Slug             string
	UserAgent        string
	AnthropicVersion string
	AnthropicBeta    string
	BetaFlags        []string
	StaticHeaders    []WireHeader
	BodyFields       []string
	BodyFieldsRequired []string
}

`)

	flavorVarNames := uniqueFlavorVarNames(snap.Flavors)
	for i, flavor := range snap.Flavors {
		varName := flavorVarNames[i]
		emitFlavorVar(&b, varName, flavor)
	}

	b.WriteString("// WireFlavors lists every flavor observed in the captured\n")
	b.WriteString("// reference. The adapter picks one at runtime based on caller\n")
	b.WriteString("// shape (interactive vs probe vs ...).\n")
	b.WriteString("var WireFlavors = []WireFlavor{\n")
	for _, name := range flavorVarNames {
		fmt.Fprintf(&b, "\t%s,\n", name)
	}
	b.WriteString("}\n")

	return b.String()
}

func uniqueFlavorVarNames(flavors []FlavorShape) []string {
	out := make([]string, 0, len(flavors))
	seen := make(map[string]int, len(flavors))
	for _, flavor := range flavors {
		base := flavorVarName(flavor.Slug)
		seen[base]++
		if seen[base] == 1 {
			out = append(out, base)
			continue
		}
		out = append(out, fmt.Sprintf("%s%d", base, seen[base]))
	}
	return out
}

func emitFlavorVar(b *strings.Builder, varName string, flavor FlavorShape) {
	fmt.Fprintf(b, "// %s is the wire shape for the %q flavor.\n", varName, flavor.Slug)
	fmt.Fprintf(b, "// Observed in %d records.\n", flavor.RecordCount)
	fmt.Fprintf(b, "var %s = WireFlavor{\n", varName)
	fmt.Fprintf(b, "\tSlug: %q,\n", flavor.Slug)

	userAgent := constantHeaderValue(flavor, "user-agent")
	anthropicVersion := constantHeaderValue(flavor, "anthropic-version")
	anthropicBeta := constantHeaderValue(flavor, "anthropic-beta")

	fmt.Fprintf(b, "\tUserAgent: %q,\n", userAgent)
	fmt.Fprintf(b, "\tAnthropicVersion: %q,\n", anthropicVersion)
	// gitleaks may flag the joined beta string as a generic-api-key
	// candidate; the value is a public Anthropic feature flag list.
	fmt.Fprintf(b, "\tAnthropicBeta: %q, // gitleaks:allow\n", anthropicBeta)

	betaFlags := splitBetaFlags(anthropicBeta)
	if len(betaFlags) == 0 {
		b.WriteString("\tBetaFlags: nil,\n")
	} else {
		// Anthropic beta flag literals are public feature names but
		// some have entropy high enough to trip generic-api-key
		// secret scanners. Mark each line so gitleaks does not
		// false-positive a regenerated reference.
		b.WriteString("\tBetaFlags: []string{\n")
		for _, flag := range betaFlags {
			fmt.Fprintf(b, "\t\t%q, // gitleaks:allow\n", flag)
		}
		b.WriteString("\t},\n")
	}

	staticHeaders := constantStaticHeaders(flavor)
	if len(staticHeaders) == 0 {
		b.WriteString("\tStaticHeaders: nil,\n")
	} else {
		b.WriteString("\tStaticHeaders: []WireHeader{\n")
		for _, h := range staticHeaders {
			fmt.Fprintf(b, "\t\t{Name: %q, Value: %q, Classification: %q},\n",
				h.Name, h.Value, h.Classification)
		}
		b.WriteString("\t},\n")
	}

	if len(flavor.Signature.BodyKeys) == 0 {
		b.WriteString("\tBodyFields: nil,\n")
	} else {
		b.WriteString("\tBodyFields: []string{\n")
		for _, k := range flavor.Signature.BodyKeys {
			fmt.Fprintf(b, "\t\t%q,\n", k)
		}
		b.WriteString("\t},\n")
	}

	required := requiredBodyFields(flavor)
	if len(required) == 0 {
		b.WriteString("\tBodyFieldsRequired: nil,\n")
	} else {
		b.WriteString("\tBodyFieldsRequired: []string{\n")
		for _, k := range required {
			fmt.Fprintf(b, "\t\t%q,\n", k)
		}
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n\n")
}

// constantHeaderValue returns the single observed value of a
// "constant"-classified header by name (case-insensitive). Returns
// "" when not constant or not present.
func constantHeaderValue(flavor FlavorShape, name string) string {
	for _, h := range flavor.Headers {
		if !strings.EqualFold(h.Name, name) {
			continue
		}
		if h.Classification == V2HeaderClassConstant && len(h.ObservedValues) == 1 {
			return h.ObservedValues[0]
		}
		return ""
	}
	return ""
}

// constantStaticHeaders returns every "constant" header except the
// well-known ones we surface as named fields (UserAgent, AnthropicBeta,
// AnthropicVersion). These remaining headers are static identity
// signals like x-app, x-stainless-*, anthropic-dangerous-*. Excludes
// auth-bearing or per-session headers (authorization, x-claude-code-session-id)
// since those carry secrets or per-session state and should not be
// codegen'd.
func constantStaticHeaders(flavor FlavorShape) []WireHeaderEmit {
	excluded := map[string]bool{
		"user-agent":               true,
		"anthropic-beta":           true,
		"anthropic-version":        true,
		"authorization":            true,
		"x-claude-code-session-id": true,
		"content-length":           true,
		"content-type":             true,
		"accept":                   true,
		"accept-encoding":          true,
		"connection":               true,
		"host":                     true,
	}
	out := make([]WireHeaderEmit, 0, len(flavor.Headers))
	for _, h := range flavor.Headers {
		if excluded[strings.ToLower(h.Name)] {
			continue
		}
		if h.Classification != V2HeaderClassConstant {
			continue
		}
		if len(h.ObservedValues) != 1 {
			continue
		}
		out = append(out, WireHeaderEmit{
			Name:           canonicalHeaderName(h.Name),
			Value:          h.ObservedValues[0],
			Classification: string(h.Classification),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// WireHeaderEmit is the codegen-time projection of a header to emit.
// It mirrors the generated WireHeader struct field names.
type WireHeaderEmit struct {
	Name           string
	Value          string
	Classification string
}

func splitBetaFlags(value string) []string {
	if strings.TrimSpace(value) == "" {
		return nil
	}
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		s := strings.TrimSpace(p)
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

func requiredBodyFields(flavor FlavorShape) []string {
	out := make([]string, 0, len(flavor.Body.Fields))
	for _, f := range flavor.Body.Fields {
		if f.Presence == V2HeaderPresenceRequired {
			out = append(out, f.Name)
		}
	}
	sort.Strings(out)
	return out
}

func flavorVarName(slug string) string {
	// e.g. "claude-code-interactive-6fde33e0" → "WireFlavorClaudeCodeInteractive"
	parts := strings.Split(slug, "-")
	keep := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Drop trailing fingerprint hex suffix (8 hex chars).
		if isHexSuffix(p) {
			continue
		}
		keep = append(keep, p)
	}
	camel := make([]string, 0, len(keep))
	for _, p := range keep {
		if len(p) == 0 {
			continue
		}
		camel = append(camel, strings.ToUpper(p[:1])+p[1:])
	}
	return "WireFlavor" + strings.Join(camel, "")
}

func isHexSuffix(s string) bool {
	if len(s) != 8 {
		return false
	}
	for _, r := range s {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') && (r < 'A' || r > 'F') {
			return false
		}
	}
	return true
}

func canonicalHeaderName(name string) string {
	parts := strings.Split(name, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return strings.Join(parts, "-")
}
