// Code generated by clyde mitm codegen. DO NOT EDIT.
// Source: /Users/agoodkind/.local/state/clyde/mitm-baselines/claude-code/reference-v2.toml
// Captured: 2026-04-30T04:30:53Z
// Upstream: claude-code
// Flavors observed: 4
//
// Run `clyde mitm codegen --package anthropic <reference.toml>` to regenerate.

package anthropic

// WireHeader is one outbound HTTP header. Name is canonical-cased.
// Value is the literal value observed in the captured reference for
// "constant"-classified headers. For "enum" and "free" headers the
// generator surfaces a sample value; the adapter is responsible for
// computing the real value at runtime.
type WireHeader struct {
	Name           string
	Value          string
	Classification string // "constant" | "enum" | "free"
}

// WireFlavor is the captured wire shape for one caller flavor of an
// upstream. Fields are typed to satisfy strict type hygiene; no
// map[string]string or interface{} appears here.
type WireFlavor struct {
	Slug               string
	UserAgent          string
	AnthropicVersion   string
	AnthropicBeta      string
	BetaFlags          []string
	StaticHeaders      []WireHeader
	BodyFields         []string
	BodyFieldsRequired []string
}

// WireFlavorClaudeCodeInteractive is the wire shape for the "claude-code-interactive-17c1f069" flavor.
// Observed in 1 records.
var WireFlavorClaudeCodeInteractive = WireFlavor{
	Slug:             "claude-code-interactive-17c1f069",
	UserAgent:        "claude-cli/2.1.123 (external, sdk-cli)",
	AnthropicVersion: "2023-06-01",
	AnthropicBeta:    "claude-code-20250219,oauth-2025-04-20,interleaved-thinking-2025-05-14,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advisor-tool-2026-03-01,effort-2025-11-24", // gitleaks:allow
	BetaFlags: []string{
		"claude-code-20250219",            // gitleaks:allow
		"oauth-2025-04-20",                // gitleaks:allow
		"interleaved-thinking-2025-05-14", // gitleaks:allow
		"context-management-2025-06-27",   // gitleaks:allow
		"prompt-caching-scope-2026-01-05", // gitleaks:allow
		"advisor-tool-2026-03-01",         // gitleaks:allow
		"effort-2025-11-24",               // gitleaks:allow
	},
	StaticHeaders: []WireHeader{
		{Name: "Anthropic-Dangerous-Direct-Browser-Access", Value: "true", Classification: "constant"},
		{Name: "X-App", Value: "cli", Classification: "constant"},
		{Name: "X-Stainless-Arch", Value: "arm64", Classification: "constant"},
		{Name: "X-Stainless-Lang", Value: "js", Classification: "constant"},
		{Name: "X-Stainless-Os", Value: "MacOS", Classification: "constant"},
		{Name: "X-Stainless-Package-Version", Value: "0.81.0", Classification: "constant"},
		{Name: "X-Stainless-Retry-Count", Value: "0", Classification: "constant"},
		{Name: "X-Stainless-Runtime", Value: "node", Classification: "constant"},
		{Name: "X-Stainless-Runtime-Version", Value: "v24.3.0", Classification: "constant"},
		{Name: "X-Stainless-Timeout", Value: "600", Classification: "constant"},
	},
	BodyFields: []string{
		"context_management",
		"max_tokens",
		"messages",
		"metadata",
		"model",
		"output_config",
		"stream",
		"system",
		"thinking",
		"tools",
	},
	BodyFieldsRequired: []string{
		"context_management",
		"max_tokens",
		"messages",
		"metadata",
		"model",
		"output_config",
		"stream",
		"system",
		"thinking",
		"tools",
	},
}

// WireFlavorClaudeCodeInteractive2 is the wire shape for the "claude-code-interactive-2dcaac1d" flavor.
// Observed in 2 records.
var WireFlavorClaudeCodeInteractive2 = WireFlavor{
	Slug:             "claude-code-interactive-2dcaac1d",
	UserAgent:        "claude-cli/2.1.121 (external, cli)",
	AnthropicVersion: "2023-06-01",
	AnthropicBeta:    "claude-code-20250219,oauth-2025-04-20,context-1m-2025-08-07,interleaved-thinking-2025-05-14,redact-thinking-2026-02-12,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advisor-tool-2026-03-01,effort-2025-11-24", // gitleaks:allow
	BetaFlags: []string{
		"claude-code-20250219",            // gitleaks:allow
		"oauth-2025-04-20",                // gitleaks:allow
		"context-1m-2025-08-07",           // gitleaks:allow
		"interleaved-thinking-2025-05-14", // gitleaks:allow
		"redact-thinking-2026-02-12",      // gitleaks:allow
		"context-management-2025-06-27",   // gitleaks:allow
		"prompt-caching-scope-2026-01-05", // gitleaks:allow
		"advisor-tool-2026-03-01",         // gitleaks:allow
		"effort-2025-11-24",               // gitleaks:allow
	},
	StaticHeaders: []WireHeader{
		{Name: "Anthropic-Dangerous-Direct-Browser-Access", Value: "true", Classification: "constant"},
		{Name: "X-App", Value: "cli", Classification: "constant"},
		{Name: "X-Stainless-Arch", Value: "arm64", Classification: "constant"},
		{Name: "X-Stainless-Lang", Value: "js", Classification: "constant"},
		{Name: "X-Stainless-Os", Value: "MacOS", Classification: "constant"},
		{Name: "X-Stainless-Package-Version", Value: "0.81.0", Classification: "constant"},
		{Name: "X-Stainless-Retry-Count", Value: "0", Classification: "constant"},
		{Name: "X-Stainless-Runtime", Value: "node", Classification: "constant"},
		{Name: "X-Stainless-Runtime-Version", Value: "v24.3.0", Classification: "constant"},
		{Name: "X-Stainless-Timeout", Value: "600", Classification: "constant"},
	},
	BodyFields: []string{
		"max_tokens",
		"messages",
		"metadata",
		"model",
		"output_config",
		"stream",
		"system",
	},
	BodyFieldsRequired: []string{
		"max_tokens",
		"messages",
		"metadata",
		"model",
		"output_config",
		"stream",
		"system",
	},
}

// WireFlavorClaudeCodeProbe is the wire shape for the "claude-code-probe-e5e49e54" flavor.
// Observed in 1 records.
var WireFlavorClaudeCodeProbe = WireFlavor{
	Slug:             "claude-code-probe-e5e49e54",
	UserAgent:        "claude-cli/2.1.123 (external, sdk-cli)",
	AnthropicVersion: "2023-06-01",
	AnthropicBeta:    "claude-code-20250219,oauth-2025-04-20,interleaved-thinking-2025-05-14,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advisor-tool-2026-03-01,effort-2025-11-24", // gitleaks:allow
	BetaFlags: []string{
		"claude-code-20250219",            // gitleaks:allow
		"oauth-2025-04-20",                // gitleaks:allow
		"interleaved-thinking-2025-05-14", // gitleaks:allow
		"context-management-2025-06-27",   // gitleaks:allow
		"prompt-caching-scope-2026-01-05", // gitleaks:allow
		"advisor-tool-2026-03-01",         // gitleaks:allow
		"effort-2025-11-24",               // gitleaks:allow
	},
	StaticHeaders: []WireHeader{
		{Name: "Anthropic-Dangerous-Direct-Browser-Access", Value: "true", Classification: "constant"},
		{Name: "X-App", Value: "cli", Classification: "constant"},
		{Name: "X-Stainless-Arch", Value: "arm64", Classification: "constant"},
		{Name: "X-Stainless-Lang", Value: "js", Classification: "constant"},
		{Name: "X-Stainless-Os", Value: "MacOS", Classification: "constant"},
		{Name: "X-Stainless-Package-Version", Value: "0.81.0", Classification: "constant"},
		{Name: "X-Stainless-Retry-Count", Value: "0", Classification: "constant"},
		{Name: "X-Stainless-Runtime", Value: "node", Classification: "constant"},
		{Name: "X-Stainless-Runtime-Version", Value: "v24.3.0", Classification: "constant"},
		{Name: "X-Stainless-Timeout", Value: "600", Classification: "constant"},
	},
	BodyFields: []string{
		"max_tokens",
		"messages",
		"model",
		"stream",
	},
	BodyFieldsRequired: []string{
		"max_tokens",
		"messages",
		"model",
		"stream",
	},
}

// WireFlavorClaudeCodeProbe2 is the wire shape for the "claude-code-probe-f711e5ef" flavor.
// Observed in 2 records.
var WireFlavorClaudeCodeProbe2 = WireFlavor{
	Slug:             "claude-code-probe-f711e5ef",
	UserAgent:        "claude-cli/2.1.121 (external, cli)",
	AnthropicVersion: "2023-06-01",
	AnthropicBeta:    "claude-code-20250219,oauth-2025-04-20,context-1m-2025-08-07,interleaved-thinking-2025-05-14,redact-thinking-2026-02-12,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advisor-tool-2026-03-01,effort-2025-11-24", // gitleaks:allow
	BetaFlags: []string{
		"claude-code-20250219",            // gitleaks:allow
		"oauth-2025-04-20",                // gitleaks:allow
		"context-1m-2025-08-07",           // gitleaks:allow
		"interleaved-thinking-2025-05-14", // gitleaks:allow
		"redact-thinking-2026-02-12",      // gitleaks:allow
		"context-management-2025-06-27",   // gitleaks:allow
		"prompt-caching-scope-2026-01-05", // gitleaks:allow
		"advisor-tool-2026-03-01",         // gitleaks:allow
		"effort-2025-11-24",               // gitleaks:allow
	},
	StaticHeaders: []WireHeader{
		{Name: "Anthropic-Dangerous-Direct-Browser-Access", Value: "true", Classification: "constant"},
		{Name: "X-App", Value: "cli", Classification: "constant"},
		{Name: "X-Stainless-Arch", Value: "arm64", Classification: "constant"},
		{Name: "X-Stainless-Lang", Value: "js", Classification: "constant"},
		{Name: "X-Stainless-Os", Value: "MacOS", Classification: "constant"},
		{Name: "X-Stainless-Package-Version", Value: "0.81.0", Classification: "constant"},
		{Name: "X-Stainless-Retry-Count", Value: "0", Classification: "constant"},
		{Name: "X-Stainless-Runtime", Value: "node", Classification: "constant"},
		{Name: "X-Stainless-Runtime-Version", Value: "v24.3.0", Classification: "constant"},
		{Name: "X-Stainless-Timeout", Value: "600", Classification: "constant"},
	},
	BodyFields: []string{
		"max_tokens",
		"messages",
		"model",
		"stream",
	},
	BodyFieldsRequired: []string{
		"max_tokens",
		"messages",
		"model",
		"stream",
	},
}

// WireFlavors lists every flavor observed in the captured
// reference. The adapter picks one at runtime based on caller
// shape (interactive vs probe vs ...).
var WireFlavors = []WireFlavor{
	WireFlavorClaudeCodeInteractive,
	WireFlavorClaudeCodeInteractive2,
	WireFlavorClaudeCodeProbe,
	WireFlavorClaudeCodeProbe2,
}
