// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/bridge.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bridge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid             int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	BridgeSessionId string                 `protobuf:"bytes,3,opt,name=bridge_session_id,json=bridgeSessionId,proto3" json:"bridge_session_id,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bridge) Reset() {
	*x = Bridge{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bridge) ProtoMessage() {}

func (x *Bridge) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bridge.ProtoReflect.Descriptor instead.
func (*Bridge) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Bridge) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Bridge) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Bridge) GetBridgeSessionId() string {
	if x != nil {
		return x.BridgeSessionId
	}
	return ""
}

func (x *Bridge) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListBridgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesRequest) Reset() {
	*x = ListBridgesRequest{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesRequest) ProtoMessage() {}

func (x *ListBridgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesRequest.ProtoReflect.Descriptor instead.
func (*ListBridgesRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{1}
}

type ListBridgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*Bridge              `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesResponse) Reset() {
	*x = ListBridgesResponse{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesResponse) ProtoMessage() {}

func (x *ListBridgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesResponse.ProtoReflect.Descriptor instead.
func (*ListBridgesResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *ListBridgesResponse) GetBridges() []*Bridge {
	if x != nil {
		return x.Bridges
	}
	return nil
}

type TailTranscriptRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// start_at_offset = 0 streams future lines only.
	StartAtOffset int64  `protobuf:"varint,2,opt,name=start_at_offset,json=startAtOffset,proto3" json:"start_at_offset,omitempty"`
	Provider      string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	SessionName   string `protobuf:"bytes,4,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailTranscriptRequest) Reset() {
	*x = TailTranscriptRequest{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailTranscriptRequest) ProtoMessage() {}

func (x *TailTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailTranscriptRequest.ProtoReflect.Descriptor instead.
func (*TailTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *TailTranscriptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TailTranscriptRequest) GetStartAtOffset() int64 {
	if x != nil {
		return x.StartAtOffset
	}
	return 0
}

func (x *TailTranscriptRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TailTranscriptRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type TailTranscriptResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ByteOffset int64                  `protobuf:"varint,1,opt,name=byte_offset,json=byteOffset,proto3" json:"byte_offset,omitempty"`
	RawJsonl   string                 `protobuf:"bytes,2,opt,name=raw_jsonl,json=rawJsonl,proto3" json:"raw_jsonl,omitempty"`
	Role       string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Text       string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Unix nanoseconds. Avoids pulling in google.protobuf.Timestamp for one field.
	TimestampNanos int64  `protobuf:"varint,5,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	Provider       string `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	SessionId      string `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionName    string `protobuf:"bytes,8,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailTranscriptResponse) Reset() {
	*x = TailTranscriptResponse{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailTranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailTranscriptResponse) ProtoMessage() {}

func (x *TailTranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailTranscriptResponse.ProtoReflect.Descriptor instead.
func (*TailTranscriptResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *TailTranscriptResponse) GetByteOffset() int64 {
	if x != nil {
		return x.ByteOffset
	}
	return 0
}

func (x *TailTranscriptResponse) GetRawJsonl() string {
	if x != nil {
		return x.RawJsonl
	}
	return ""
}

func (x *TailTranscriptResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TailTranscriptResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TailTranscriptResponse) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

func (x *TailTranscriptResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TailTranscriptResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TailTranscriptResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type SendToSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	SessionName   string                 `protobuf:"bytes,4,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToSessionRequest) Reset() {
	*x = SendToSessionRequest{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToSessionRequest) ProtoMessage() {}

func (x *SendToSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToSessionRequest.ProtoReflect.Descriptor instead.
func (*SendToSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *SendToSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendToSessionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendToSessionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SendToSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type SendToSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int32                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Delivered     bool                   `protobuf:"varint,2,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToSessionResponse) Reset() {
	*x = SendToSessionResponse{}
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToSessionResponse) ProtoMessage() {}

func (x *SendToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToSessionResponse.ProtoReflect.Descriptor instead.
func (*SendToSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *SendToSessionResponse) GetBytesWritten() int32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *SendToSessionResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

var File_clyde_v1_daemon_bridge_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_bridge_proto_rawDesc = "" +
	"\n" +
	"\x1cclyde/v1/daemon/bridge.proto\x12\bclyde.v1\"w\n" +
	"\x06Bridge\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12*\n" +
	"\x11bridge_session_id\x18\x03 \x01(\tR\x0fbridgeSessionId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\x14\n" +
	"\x12ListBridgesRequest\"A\n" +
	"\x13ListBridgesResponse\x12*\n" +
	"\abridges\x18\x01 \x03(\v2\x10.clyde.v1.BridgeR\abridges\"\x9d\x01\n" +
	"\x15TailTranscriptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\x0fstart_at_offset\x18\x02 \x01(\x03R\rstartAtOffset\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12!\n" +
	"\fsession_name\x18\x04 \x01(\tR\vsessionName\"\x85\x02\n" +
	"\x16TailTranscriptResponse\x12\x1f\n" +
	"\vbyte_offset\x18\x01 \x01(\x03R\n" +
	"byteOffset\x12\x1b\n" +
	"\traw_jsonl\x18\x02 \x01(\tR\brawJsonl\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12'\n" +
	"\x0ftimestamp_nanos\x18\x05 \x01(\x03R\x0etimestampNanos\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12!\n" +
	"\fsession_name\x18\b \x01(\tR\vsessionName\"\x88\x01\n" +
	"\x14SendToSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12!\n" +
	"\fsession_name\x18\x04 \x01(\tR\vsessionName\"Z\n" +
	"\x15SendToSessionResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x05R\fbytesWritten\x12\x1c\n" +
	"\tdelivered\x18\x02 \x01(\bR\tdeliveredB(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_bridge_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_bridge_proto_rawDescData []byte
)

func file_clyde_v1_daemon_bridge_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_bridge_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_bridge_proto_rawDesc), len(file_clyde_v1_daemon_bridge_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_bridge_proto_rawDescData
}

var file_clyde_v1_daemon_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_clyde_v1_daemon_bridge_proto_goTypes = []any{
	(*Bridge)(nil),                 // 0: clyde.v1.Bridge
	(*ListBridgesRequest)(nil),     // 1: clyde.v1.ListBridgesRequest
	(*ListBridgesResponse)(nil),    // 2: clyde.v1.ListBridgesResponse
	(*TailTranscriptRequest)(nil),  // 3: clyde.v1.TailTranscriptRequest
	(*TailTranscriptResponse)(nil), // 4: clyde.v1.TailTranscriptResponse
	(*SendToSessionRequest)(nil),   // 5: clyde.v1.SendToSessionRequest
	(*SendToSessionResponse)(nil),  // 6: clyde.v1.SendToSessionResponse
}
var file_clyde_v1_daemon_bridge_proto_depIdxs = []int32{
	0, // 0: clyde.v1.ListBridgesResponse.bridges:type_name -> clyde.v1.Bridge
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_bridge_proto_init() }
func file_clyde_v1_daemon_bridge_proto_init() {
	if File_clyde_v1_daemon_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_bridge_proto_rawDesc), len(file_clyde_v1_daemon_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_bridge_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_bridge_proto_depIdxs,
		MessageInfos:      file_clyde_v1_daemon_bridge_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_bridge_proto = out.File
	file_clyde_v1_daemon_bridge_proto_goTypes = nil
	file_clyde_v1_daemon_bridge_proto_depIdxs = nil
}
