// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/context.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeContextUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeContextUsageRequest) Reset() {
	*x = ProbeContextUsageRequest{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeContextUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeContextUsageRequest) ProtoMessage() {}

func (x *ProbeContextUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeContextUsageRequest.ProtoReflect.Descriptor instead.
func (*ProbeContextUsageRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeContextUsageRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type ContextUsageCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tokens        int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	IsDeferred    bool                   `protobuf:"varint,4,opt,name=is_deferred,json=isDeferred,proto3" json:"is_deferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUsageCategory) Reset() {
	*x = ContextUsageCategory{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUsageCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUsageCategory) ProtoMessage() {}

func (x *ContextUsageCategory) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUsageCategory.ProtoReflect.Descriptor instead.
func (*ContextUsageCategory) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{1}
}

func (x *ContextUsageCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContextUsageCategory) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *ContextUsageCategory) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ContextUsageCategory) GetIsDeferred() bool {
	if x != nil {
		return x.IsDeferred
	}
	return false
}

type ProbeContextUsageResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionName   string                  `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionId     string                  `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model         string                  `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	TotalTokens   int32                   `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	MaxTokens     int32                   `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Percentage    int32                   `protobuf:"varint,6,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Categories    []*ContextUsageCategory `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeContextUsageResponse) Reset() {
	*x = ProbeContextUsageResponse{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeContextUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeContextUsageResponse) ProtoMessage() {}

func (x *ProbeContextUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeContextUsageResponse.ProtoReflect.Descriptor instead.
func (*ProbeContextUsageResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeContextUsageResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ProbeContextUsageResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProbeContextUsageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProbeContextUsageResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ProbeContextUsageResponse) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ProbeContextUsageResponse) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProbeContextUsageResponse) GetCategories() []*ContextUsageCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_clyde_v1_daemon_context_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_context_proto_rawDesc = "" +
	"\n" +
	"\x1dclyde/v1/daemon/context.proto\x12\bclyde.v1\"=\n" +
	"\x18ProbeContextUsageRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\"y\n" +
	"\x14ContextUsageCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1f\n" +
	"\vis_deferred\x18\x04 \x01(\bR\n" +
	"isDeferred\"\x95\x02\n" +
	"\x19ProbeContextUsageResponse\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x1e\n" +
	"\n" +
	"percentage\x18\x06 \x01(\x05R\n" +
	"percentage\x12>\n" +
	"\n" +
	"categories\x18\a \x03(\v2\x1e.clyde.v1.ContextUsageCategoryR\n" +
	"categoriesB(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_context_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_context_proto_rawDescData []byte
)

func file_clyde_v1_daemon_context_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_context_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_context_proto_rawDesc), len(file_clyde_v1_daemon_context_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_context_proto_rawDescData
}

var file_clyde_v1_daemon_context_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clyde_v1_daemon_context_proto_goTypes = []any{
	(*ProbeContextUsageRequest)(nil),  // 0: clyde.v1.ProbeContextUsageRequest
	(*ContextUsageCategory)(nil),      // 1: clyde.v1.ContextUsageCategory
	(*ProbeContextUsageResponse)(nil), // 2: clyde.v1.ProbeContextUsageResponse
}
var file_clyde_v1_daemon_context_proto_depIdxs = []int32{
	1, // 0: clyde.v1.ProbeContextUsageResponse.categories:type_name -> clyde.v1.ContextUsageCategory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_context_proto_init() }
func file_clyde_v1_daemon_context_proto_init() {
	if File_clyde_v1_daemon_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_context_proto_rawDesc), len(file_clyde_v1_daemon_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_context_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_context_proto_depIdxs,
		MessageInfos:      file_clyde_v1_daemon_context_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_context_proto = out.File
	file_clyde_v1_daemon_context_proto_goTypes = nil
	file_clyde_v1_daemon_context_proto_depIdxs = nil
}
