// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: clyde/v1/daemon.proto

package clydev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClydeService_AcquireSession_FullMethodName        = "/clyde.v1.ClydeService/AcquireSession"
	ClydeService_ReleaseSession_FullMethodName        = "/clyde.v1.ClydeService/ReleaseSession"
	ClydeService_HookEvent_FullMethodName             = "/clyde.v1.ClydeService/HookEvent"
	ClydeService_ListActiveSessions_FullMethodName    = "/clyde.v1.ClydeService/ListActiveSessions"
	ClydeService_TriggerScan_FullMethodName           = "/clyde.v1.ClydeService/TriggerScan"
	ClydeService_SubscribeRegistry_FullMethodName     = "/clyde.v1.ClydeService/SubscribeRegistry"
	ClydeService_RenameSession_FullMethodName         = "/clyde.v1.ClydeService/RenameSession"
	ClydeService_DeleteSession_FullMethodName         = "/clyde.v1.ClydeService/DeleteSession"
	ClydeService_UpdateSessionSettings_FullMethodName = "/clyde.v1.ClydeService/UpdateSessionSettings"
	ClydeService_UpdateGlobalSettings_FullMethodName  = "/clyde.v1.ClydeService/UpdateGlobalSettings"
	ClydeService_ListBridges_FullMethodName           = "/clyde.v1.ClydeService/ListBridges"
	ClydeService_TailTranscript_FullMethodName        = "/clyde.v1.ClydeService/TailTranscript"
	ClydeService_SendToSession_FullMethodName         = "/clyde.v1.ClydeService/SendToSession"
)

// ClydeServiceClient is the client API for ClydeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClydeServiceClient interface {
	AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error)
	ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error)
	HookEvent(ctx context.Context, in *HookEventRequest, opts ...grpc.CallOption) (*HookEventResponse, error)
	ListActiveSessions(ctx context.Context, in *ListActiveSessionsRequest, opts ...grpc.CallOption) (*ListActiveSessionsResponse, error)
	TriggerScan(ctx context.Context, in *TriggerScanRequest, opts ...grpc.CallOption) (*TriggerScanResponse, error)
	SubscribeRegistry(ctx context.Context, in *SubscribeRegistryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeRegistryResponse], error)
	RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*RenameSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	UpdateSessionSettings(ctx context.Context, in *UpdateSessionSettingsRequest, opts ...grpc.CallOption) (*UpdateSessionSettingsResponse, error)
	UpdateGlobalSettings(ctx context.Context, in *UpdateGlobalSettingsRequest, opts ...grpc.CallOption) (*UpdateGlobalSettingsResponse, error)
	ListBridges(ctx context.Context, in *ListBridgesRequest, opts ...grpc.CallOption) (*ListBridgesResponse, error)
	TailTranscript(ctx context.Context, in *TailTranscriptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailTranscriptResponse], error)
	SendToSession(ctx context.Context, in *SendToSessionRequest, opts ...grpc.CallOption) (*SendToSessionResponse, error)
}

type clydeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClydeServiceClient(cc grpc.ClientConnInterface) ClydeServiceClient {
	return &clydeServiceClient{cc}
}

func (c *clydeServiceClient) AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireSessionResponse)
	err := c.cc.Invoke(ctx, ClydeService_AcquireSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSessionResponse)
	err := c.cc.Invoke(ctx, ClydeService_ReleaseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) HookEvent(ctx context.Context, in *HookEventRequest, opts ...grpc.CallOption) (*HookEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookEventResponse)
	err := c.cc.Invoke(ctx, ClydeService_HookEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) ListActiveSessions(ctx context.Context, in *ListActiveSessionsRequest, opts ...grpc.CallOption) (*ListActiveSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveSessionsResponse)
	err := c.cc.Invoke(ctx, ClydeService_ListActiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) TriggerScan(ctx context.Context, in *TriggerScanRequest, opts ...grpc.CallOption) (*TriggerScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerScanResponse)
	err := c.cc.Invoke(ctx, ClydeService_TriggerScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) SubscribeRegistry(ctx context.Context, in *SubscribeRegistryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeRegistryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClydeService_ServiceDesc.Streams[0], ClydeService_SubscribeRegistry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRegistryRequest, SubscribeRegistryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClydeService_SubscribeRegistryClient = grpc.ServerStreamingClient[SubscribeRegistryResponse]

func (c *clydeServiceClient) RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*RenameSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameSessionResponse)
	err := c.cc.Invoke(ctx, ClydeService_RenameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, ClydeService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) UpdateSessionSettings(ctx context.Context, in *UpdateSessionSettingsRequest, opts ...grpc.CallOption) (*UpdateSessionSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionSettingsResponse)
	err := c.cc.Invoke(ctx, ClydeService_UpdateSessionSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) UpdateGlobalSettings(ctx context.Context, in *UpdateGlobalSettingsRequest, opts ...grpc.CallOption) (*UpdateGlobalSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGlobalSettingsResponse)
	err := c.cc.Invoke(ctx, ClydeService_UpdateGlobalSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) ListBridges(ctx context.Context, in *ListBridgesRequest, opts ...grpc.CallOption) (*ListBridgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBridgesResponse)
	err := c.cc.Invoke(ctx, ClydeService_ListBridges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) TailTranscript(ctx context.Context, in *TailTranscriptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailTranscriptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClydeService_ServiceDesc.Streams[1], ClydeService_TailTranscript_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailTranscriptRequest, TailTranscriptResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClydeService_TailTranscriptClient = grpc.ServerStreamingClient[TailTranscriptResponse]

func (c *clydeServiceClient) SendToSession(ctx context.Context, in *SendToSessionRequest, opts ...grpc.CallOption) (*SendToSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToSessionResponse)
	err := c.cc.Invoke(ctx, ClydeService_SendToSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClydeServiceServer is the server API for ClydeService service.
// All implementations should embed UnimplementedClydeServiceServer
// for forward compatibility.
type ClydeServiceServer interface {
	AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error)
	ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error)
	HookEvent(context.Context, *HookEventRequest) (*HookEventResponse, error)
	ListActiveSessions(context.Context, *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error)
	TriggerScan(context.Context, *TriggerScanRequest) (*TriggerScanResponse, error)
	SubscribeRegistry(*SubscribeRegistryRequest, grpc.ServerStreamingServer[SubscribeRegistryResponse]) error
	RenameSession(context.Context, *RenameSessionRequest) (*RenameSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	UpdateSessionSettings(context.Context, *UpdateSessionSettingsRequest) (*UpdateSessionSettingsResponse, error)
	UpdateGlobalSettings(context.Context, *UpdateGlobalSettingsRequest) (*UpdateGlobalSettingsResponse, error)
	ListBridges(context.Context, *ListBridgesRequest) (*ListBridgesResponse, error)
	TailTranscript(*TailTranscriptRequest, grpc.ServerStreamingServer[TailTranscriptResponse]) error
	SendToSession(context.Context, *SendToSessionRequest) (*SendToSessionResponse, error)
}

// UnimplementedClydeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClydeServiceServer struct{}

func (UnimplementedClydeServiceServer) AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireSession not implemented")
}
func (UnimplementedClydeServiceServer) ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSession not implemented")
}
func (UnimplementedClydeServiceServer) HookEvent(context.Context, *HookEventRequest) (*HookEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HookEvent not implemented")
}
func (UnimplementedClydeServiceServer) ListActiveSessions(context.Context, *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveSessions not implemented")
}
func (UnimplementedClydeServiceServer) TriggerScan(context.Context, *TriggerScanRequest) (*TriggerScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerScan not implemented")
}
func (UnimplementedClydeServiceServer) SubscribeRegistry(*SubscribeRegistryRequest, grpc.ServerStreamingServer[SubscribeRegistryResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRegistry not implemented")
}
func (UnimplementedClydeServiceServer) RenameSession(context.Context, *RenameSessionRequest) (*RenameSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSession not implemented")
}
func (UnimplementedClydeServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedClydeServiceServer) UpdateSessionSettings(context.Context, *UpdateSessionSettingsRequest) (*UpdateSessionSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionSettings not implemented")
}
func (UnimplementedClydeServiceServer) UpdateGlobalSettings(context.Context, *UpdateGlobalSettingsRequest) (*UpdateGlobalSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGlobalSettings not implemented")
}
func (UnimplementedClydeServiceServer) ListBridges(context.Context, *ListBridgesRequest) (*ListBridgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBridges not implemented")
}
func (UnimplementedClydeServiceServer) TailTranscript(*TailTranscriptRequest, grpc.ServerStreamingServer[TailTranscriptResponse]) error {
	return status.Error(codes.Unimplemented, "method TailTranscript not implemented")
}
func (UnimplementedClydeServiceServer) SendToSession(context.Context, *SendToSessionRequest) (*SendToSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToSession not implemented")
}
func (UnimplementedClydeServiceServer) testEmbeddedByValue() {}

// UnsafeClydeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClydeServiceServer will
// result in compilation errors.
type UnsafeClydeServiceServer interface {
	mustEmbedUnimplementedClydeServiceServer()
}

func RegisterClydeServiceServer(s grpc.ServiceRegistrar, srv ClydeServiceServer) {
	// If the following call panics, it indicates UnimplementedClydeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClydeService_ServiceDesc, srv)
}

func _ClydeService_AcquireSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).AcquireSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_AcquireSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).AcquireSession(ctx, req.(*AcquireSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_ReleaseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).ReleaseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_ReleaseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).ReleaseSession(ctx, req.(*ReleaseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_HookEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).HookEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_HookEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).HookEvent(ctx, req.(*HookEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_ListActiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).ListActiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_ListActiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).ListActiveSessions(ctx, req.(*ListActiveSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_TriggerScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).TriggerScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_TriggerScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).TriggerScan(ctx, req.(*TriggerScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_SubscribeRegistry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRegistryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClydeServiceServer).SubscribeRegistry(m, &grpc.GenericServerStream[SubscribeRegistryRequest, SubscribeRegistryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClydeService_SubscribeRegistryServer = grpc.ServerStreamingServer[SubscribeRegistryResponse]

func _ClydeService_RenameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).RenameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_RenameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).RenameSession(ctx, req.(*RenameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_UpdateSessionSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).UpdateSessionSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_UpdateSessionSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).UpdateSessionSettings(ctx, req.(*UpdateSessionSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_UpdateGlobalSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGlobalSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).UpdateGlobalSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_UpdateGlobalSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).UpdateGlobalSettings(ctx, req.(*UpdateGlobalSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_ListBridges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).ListBridges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_ListBridges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).ListBridges(ctx, req.(*ListBridgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_TailTranscript_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailTranscriptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClydeServiceServer).TailTranscript(m, &grpc.GenericServerStream[TailTranscriptRequest, TailTranscriptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClydeService_TailTranscriptServer = grpc.ServerStreamingServer[TailTranscriptResponse]

func _ClydeService_SendToSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).SendToSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_SendToSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).SendToSession(ctx, req.(*SendToSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClydeService_ServiceDesc is the grpc.ServiceDesc for ClydeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClydeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clyde.v1.ClydeService",
	HandlerType: (*ClydeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireSession",
			Handler:    _ClydeService_AcquireSession_Handler,
		},
		{
			MethodName: "ReleaseSession",
			Handler:    _ClydeService_ReleaseSession_Handler,
		},
		{
			MethodName: "HookEvent",
			Handler:    _ClydeService_HookEvent_Handler,
		},
		{
			MethodName: "ListActiveSessions",
			Handler:    _ClydeService_ListActiveSessions_Handler,
		},
		{
			MethodName: "TriggerScan",
			Handler:    _ClydeService_TriggerScan_Handler,
		},
		{
			MethodName: "RenameSession",
			Handler:    _ClydeService_RenameSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _ClydeService_DeleteSession_Handler,
		},
		{
			MethodName: "UpdateSessionSettings",
			Handler:    _ClydeService_UpdateSessionSettings_Handler,
		},
		{
			MethodName: "UpdateGlobalSettings",
			Handler:    _ClydeService_UpdateGlobalSettings_Handler,
		},
		{
			MethodName: "ListBridges",
			Handler:    _ClydeService_ListBridges_Handler,
		},
		{
			MethodName: "SendToSession",
			Handler:    _ClydeService_SendToSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRegistry",
			Handler:       _ClydeService_SubscribeRegistry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TailTranscript",
			Handler:       _ClydeService_TailTranscript_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clyde/v1/daemon.proto",
}
