// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/registry.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRegistryResponse_Kind int32

const (
	SubscribeRegistryResponse_KIND_UNSPECIFIED             SubscribeRegistryResponse_Kind = 0
	SubscribeRegistryResponse_KIND_SESSION_ADOPTED         SubscribeRegistryResponse_Kind = 1
	SubscribeRegistryResponse_KIND_SESSION_UPDATED         SubscribeRegistryResponse_Kind = 2
	SubscribeRegistryResponse_KIND_SESSION_DELETED         SubscribeRegistryResponse_Kind = 3
	SubscribeRegistryResponse_KIND_SESSION_RENAMED         SubscribeRegistryResponse_Kind = 4
	SubscribeRegistryResponse_KIND_BRIDGE_OPENED           SubscribeRegistryResponse_Kind = 5
	SubscribeRegistryResponse_KIND_BRIDGE_CLOSED           SubscribeRegistryResponse_Kind = 6
	SubscribeRegistryResponse_KIND_GLOBAL_SETTINGS_UPDATED SubscribeRegistryResponse_Kind = 7
	SubscribeRegistryResponse_KIND_CLYDE_BINARY_UPDATED    SubscribeRegistryResponse_Kind = 8
)

// Enum value maps for SubscribeRegistryResponse_Kind.
var (
	SubscribeRegistryResponse_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SESSION_ADOPTED",
		2: "KIND_SESSION_UPDATED",
		3: "KIND_SESSION_DELETED",
		4: "KIND_SESSION_RENAMED",
		5: "KIND_BRIDGE_OPENED",
		6: "KIND_BRIDGE_CLOSED",
		7: "KIND_GLOBAL_SETTINGS_UPDATED",
		8: "KIND_CLYDE_BINARY_UPDATED",
	}
	SubscribeRegistryResponse_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":             0,
		"KIND_SESSION_ADOPTED":         1,
		"KIND_SESSION_UPDATED":         2,
		"KIND_SESSION_DELETED":         3,
		"KIND_SESSION_RENAMED":         4,
		"KIND_BRIDGE_OPENED":           5,
		"KIND_BRIDGE_CLOSED":           6,
		"KIND_GLOBAL_SETTINGS_UPDATED": 7,
		"KIND_CLYDE_BINARY_UPDATED":    8,
	}
)

func (x SubscribeRegistryResponse_Kind) Enum() *SubscribeRegistryResponse_Kind {
	p := new(SubscribeRegistryResponse_Kind)
	*p = x
	return p
}

func (x SubscribeRegistryResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeRegistryResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_registry_proto_enumTypes[0].Descriptor()
}

func (SubscribeRegistryResponse_Kind) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_registry_proto_enumTypes[0]
}

func (x SubscribeRegistryResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeRegistryResponse_Kind.Descriptor instead.
func (SubscribeRegistryResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{5, 0}
}

type TriggerScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScanRequest) Reset() {
	*x = TriggerScanRequest{}
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScanRequest) ProtoMessage() {}

func (x *TriggerScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScanRequest.ProtoReflect.Descriptor instead.
func (*TriggerScanRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{0}
}

type TriggerScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdoptedCount  int32                  `protobuf:"varint,1,opt,name=adopted_count,json=adoptedCount,proto3" json:"adopted_count,omitempty"`
	AdoptedNames  []string               `protobuf:"bytes,2,rep,name=adopted_names,json=adoptedNames,proto3" json:"adopted_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScanResponse) Reset() {
	*x = TriggerScanResponse{}
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScanResponse) ProtoMessage() {}

func (x *TriggerScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScanResponse.ProtoReflect.Descriptor instead.
func (*TriggerScanResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerScanResponse) GetAdoptedCount() int32 {
	if x != nil {
		return x.AdoptedCount
	}
	return 0
}

func (x *TriggerScanResponse) GetAdoptedNames() []string {
	if x != nil {
		return x.AdoptedNames
	}
	return nil
}

type ReloadDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadDaemonRequest) Reset() {
	*x = ReloadDaemonRequest{}
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDaemonRequest) ProtoMessage() {}

func (x *ReloadDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDaemonRequest.ProtoReflect.Descriptor instead.
func (*ReloadDaemonRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{2}
}

type ReloadDaemonResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveSessions int32                  `protobuf:"varint,1,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	BinaryReloaded bool                   `protobuf:"varint,2,opt,name=binary_reloaded,json=binaryReloaded,proto3" json:"binary_reloaded,omitempty"`
	NewPid         int64                  `protobuf:"varint,3,opt,name=new_pid,json=newPid,proto3" json:"new_pid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReloadDaemonResponse) Reset() {
	*x = ReloadDaemonResponse{}
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDaemonResponse) ProtoMessage() {}

func (x *ReloadDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDaemonResponse.ProtoReflect.Descriptor instead.
func (*ReloadDaemonResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ReloadDaemonResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *ReloadDaemonResponse) GetBinaryReloaded() bool {
	if x != nil {
		return x.BinaryReloaded
	}
	return false
}

func (x *ReloadDaemonResponse) GetNewPid() int64 {
	if x != nil {
		return x.NewPid
	}
	return 0
}

type SubscribeRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRegistryRequest) Reset() {
	*x = SubscribeRegistryRequest{}
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRegistryRequest) ProtoMessage() {}

func (x *SubscribeRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRegistryRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRegistryRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{4}
}

type SubscribeRegistryResponse struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	Kind                SubscribeRegistryResponse_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=clyde.v1.SubscribeRegistryResponse_Kind" json:"kind,omitempty"`
	SessionName         string                         `protobuf:"bytes,2,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionId           string                         `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OldName             string                         `protobuf:"bytes,4,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	BridgeSessionId     string                         `protobuf:"bytes,5,opt,name=bridge_session_id,json=bridgeSessionId,proto3" json:"bridge_session_id,omitempty"`
	BridgeUrl           string                         `protobuf:"bytes,6,opt,name=bridge_url,json=bridgeUrl,proto3" json:"bridge_url,omitempty"`
	SessionSummary      *SessionSummary                `protobuf:"bytes,7,opt,name=session_summary,json=sessionSummary,proto3" json:"session_summary,omitempty"`
	GlobalRemoteControl bool                           `protobuf:"varint,8,opt,name=global_remote_control,json=globalRemoteControl,proto3" json:"global_remote_control,omitempty"`
	BinaryPath          string                         `protobuf:"bytes,9,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	BinaryReason        string                         `protobuf:"bytes,10,opt,name=binary_reason,json=binaryReason,proto3" json:"binary_reason,omitempty"`
	BinaryHash          string                         `protobuf:"bytes,11,opt,name=binary_hash,json=binaryHash,proto3" json:"binary_hash,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeRegistryResponse) Reset() {
	*x = SubscribeRegistryResponse{}
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRegistryResponse) ProtoMessage() {}

func (x *SubscribeRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRegistryResponse.ProtoReflect.Descriptor instead.
func (*SubscribeRegistryResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_registry_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRegistryResponse) GetKind() SubscribeRegistryResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return SubscribeRegistryResponse_KIND_UNSPECIFIED
}

func (x *SubscribeRegistryResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetBridgeSessionId() string {
	if x != nil {
		return x.BridgeSessionId
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetBridgeUrl() string {
	if x != nil {
		return x.BridgeUrl
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetSessionSummary() *SessionSummary {
	if x != nil {
		return x.SessionSummary
	}
	return nil
}

func (x *SubscribeRegistryResponse) GetGlobalRemoteControl() bool {
	if x != nil {
		return x.GlobalRemoteControl
	}
	return false
}

func (x *SubscribeRegistryResponse) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetBinaryReason() string {
	if x != nil {
		return x.BinaryReason
	}
	return ""
}

func (x *SubscribeRegistryResponse) GetBinaryHash() string {
	if x != nil {
		return x.BinaryHash
	}
	return ""
}

var File_clyde_v1_daemon_registry_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_registry_proto_rawDesc = "" +
	"\n" +
	"\x1eclyde/v1/daemon/registry.proto\x12\bclyde.v1\x1a\x1dclyde/v1/daemon/session.proto\"\x14\n" +
	"\x12TriggerScanRequest\"_\n" +
	"\x13TriggerScanResponse\x12#\n" +
	"\radopted_count\x18\x01 \x01(\x05R\fadoptedCount\x12#\n" +
	"\radopted_names\x18\x02 \x03(\tR\fadoptedNames\"\x15\n" +
	"\x13ReloadDaemonRequest\"\x81\x01\n" +
	"\x14ReloadDaemonResponse\x12'\n" +
	"\x0factive_sessions\x18\x01 \x01(\x05R\x0eactiveSessions\x12'\n" +
	"\x0fbinary_reloaded\x18\x02 \x01(\bR\x0ebinaryReloaded\x12\x17\n" +
	"\anew_pid\x18\x03 \x01(\x03R\x06newPid\"\x1a\n" +
	"\x18SubscribeRegistryRequest\"\xd7\x05\n" +
	"\x19SubscribeRegistryResponse\x12<\n" +
	"\x04kind\x18\x01 \x01(\x0e2(.clyde.v1.SubscribeRegistryResponse.KindR\x04kind\x12!\n" +
	"\fsession_name\x18\x02 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\bold_name\x18\x04 \x01(\tR\aoldName\x12*\n" +
	"\x11bridge_session_id\x18\x05 \x01(\tR\x0fbridgeSessionId\x12\x1d\n" +
	"\n" +
	"bridge_url\x18\x06 \x01(\tR\tbridgeUrl\x12A\n" +
	"\x0fsession_summary\x18\a \x01(\v2\x18.clyde.v1.SessionSummaryR\x0esessionSummary\x122\n" +
	"\x15global_remote_control\x18\b \x01(\bR\x13globalRemoteControl\x12\x1f\n" +
	"\vbinary_path\x18\t \x01(\tR\n" +
	"binaryPath\x12#\n" +
	"\rbinary_reason\x18\n" +
	" \x01(\tR\fbinaryReason\x12\x1f\n" +
	"\vbinary_hash\x18\v \x01(\tR\n" +
	"binaryHash\"\xf5\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14KIND_SESSION_ADOPTED\x10\x01\x12\x18\n" +
	"\x14KIND_SESSION_UPDATED\x10\x02\x12\x18\n" +
	"\x14KIND_SESSION_DELETED\x10\x03\x12\x18\n" +
	"\x14KIND_SESSION_RENAMED\x10\x04\x12\x16\n" +
	"\x12KIND_BRIDGE_OPENED\x10\x05\x12\x16\n" +
	"\x12KIND_BRIDGE_CLOSED\x10\x06\x12 \n" +
	"\x1cKIND_GLOBAL_SETTINGS_UPDATED\x10\a\x12\x1d\n" +
	"\x19KIND_CLYDE_BINARY_UPDATED\x10\bB(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_registry_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_registry_proto_rawDescData []byte
)

func file_clyde_v1_daemon_registry_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_registry_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_registry_proto_rawDesc), len(file_clyde_v1_daemon_registry_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_registry_proto_rawDescData
}

var file_clyde_v1_daemon_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clyde_v1_daemon_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_clyde_v1_daemon_registry_proto_goTypes = []any{
	(SubscribeRegistryResponse_Kind)(0), // 0: clyde.v1.SubscribeRegistryResponse.Kind
	(*TriggerScanRequest)(nil),          // 1: clyde.v1.TriggerScanRequest
	(*TriggerScanResponse)(nil),         // 2: clyde.v1.TriggerScanResponse
	(*ReloadDaemonRequest)(nil),         // 3: clyde.v1.ReloadDaemonRequest
	(*ReloadDaemonResponse)(nil),        // 4: clyde.v1.ReloadDaemonResponse
	(*SubscribeRegistryRequest)(nil),    // 5: clyde.v1.SubscribeRegistryRequest
	(*SubscribeRegistryResponse)(nil),   // 6: clyde.v1.SubscribeRegistryResponse
	(*SessionSummary)(nil),              // 7: clyde.v1.SessionSummary
}
var file_clyde_v1_daemon_registry_proto_depIdxs = []int32{
	0, // 0: clyde.v1.SubscribeRegistryResponse.kind:type_name -> clyde.v1.SubscribeRegistryResponse.Kind
	7, // 1: clyde.v1.SubscribeRegistryResponse.session_summary:type_name -> clyde.v1.SessionSummary
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_registry_proto_init() }
func file_clyde_v1_daemon_registry_proto_init() {
	if File_clyde_v1_daemon_registry_proto != nil {
		return
	}
	file_clyde_v1_daemon_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_registry_proto_rawDesc), len(file_clyde_v1_daemon_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_registry_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_registry_proto_depIdxs,
		EnumInfos:         file_clyde_v1_daemon_registry_proto_enumTypes,
		MessageInfos:      file_clyde_v1_daemon_registry_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_registry_proto = out.File
	file_clyde_v1_daemon_registry_proto_goTypes = nil
	file_clyde_v1_daemon_registry_proto_depIdxs = nil
}
