package cmd

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/fgrehm/clotilde/internal/session"
	"github.com/fgrehm/clotilde/internal/transcript"
)

// kebabRe validates a generated display name: lowercase letters, digits, hyphens only.
var kebabRe = regexp.MustCompile(`^[a-z][a-z0-9-]{1,48}[a-z0-9]$`)

// defaultNameRe matches auto-generated default names that carry no useful
// human information. Two patterns qualify:
//
//	someuser-<8hex>  (the login-prefix fallback, for example agoodkind-dfb689bc)
//	YYYY-MM-DD-word-word  (the date-prefixed random pair, for example 2026-04-13-nice-hawk)
//
// isDefaultName also flags names where the word portion is empty or looks
// like a UUID fragment, so --unnamed-only can quickly pick them up.
var defaultNameRe = regexp.MustCompile(`^(?:[a-z0-9]+-[0-9a-f]{6,}|\d{4}-\d{2}-\d{2}-[a-z]+-[a-z]+)$`)

// isDefaultName reports whether a session name looks auto-generated by the
// default session.NewSession pattern or the date-prefix fallback.
func isDefaultName(name string) bool {
	return defaultNameRe.MatchString(name)
}

func newAutoNameCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auto-name [<session>...]",
		Short: "Generate human-readable names for sessions using LLM and rename them",
		Long: `auto-name uses a fast LLM (claude haiku) to generate a short kebab-case
name for one or more sessions based on the conversation content.
The session directory is renamed to the new name (e.g. "opnsense-bgp-cutover"
instead of "configs-6d383f1d").

Examples:
  clotilde auto-name configs-6d383f1d                # rename one session
  clotilde auto-name --all                           # rename all sessions
  clotilde auto-name --all --dry-run                 # preview without saving
  clotilde auto-name --unnamed-only                  # only default-pattern names
  clotilde auto-name --unnamed-only --limit 10       # cap to the 10 most recent`,
		Args:              cobra.ArbitraryArgs,
		ValidArgsFunction: sessionNameCompletion,
		RunE: func(cmd *cobra.Command, args []string) error {
			all, _ := cmd.Flags().GetBool("all")
			unnamedOnly, _ := cmd.Flags().GetBool("unnamed-only")
			limit, _ := cmd.Flags().GetInt("limit")
			dryRun, _ := cmd.Flags().GetBool("dry-run")
			model, _ := cmd.Flags().GetString("model")
			if model == "" {
				model = "haiku"
			}

			store, err := globalStore()
			if err != nil {
				return err
			}

			var targets []*session.Session

			if all || unnamedOnly {
				list, listErr := store.List()
				if listErr != nil {
					return fmt.Errorf("failed to list sessions: %w", listErr)
				}
				for _, s := range list {
					if s.Metadata.IsIncognito {
						continue
					}
					if unnamedOnly && !isDefaultName(s.Name) {
						continue
					}
					targets = append(targets, s)
				}
				if limit > 0 && len(targets) > limit {
					// List is already sorted by most recent first in the store.
					targets = targets[:limit]
				}
			} else {
				if len(args) == 0 {
					return fmt.Errorf("provide session name(s) or use --all")
				}
				for _, name := range args {
					s, getErr := store.Get(name)
					if getErr != nil {
						return fmt.Errorf("session '%s' not found", name)
					}
					targets = append(targets, s)
				}
			}

			if len(targets) == 0 {
				_, _ = fmt.Fprintln(cmd.OutOrStdout(), "No sessions to rename.")
				return nil
			}

			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Generating names for %d session(s)...\n", len(targets))

			succeeded := 0
			for _, sess := range targets {
				name, genErr := generateName(nil, sess, "", nil, model)
				if genErr != nil {
					_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  SKIP %s: %v\n", sess.Name, genErr)
					continue
				}

				if dryRun {
					_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  DRY  %s  =>  %s\n", sess.Name, name)
					continue
				}

				if renameErr := store.Rename(sess.Name, name); renameErr != nil {
					_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  FAIL %s: %v\n", sess.Name, renameErr)
					continue
				}

				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  OK   %s  =>  %s\n", sess.Name, name)
				succeeded++
			}

			if !dryRun {
				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "\nDone. %d/%d sessions renamed.\n", succeeded, len(targets))
			}
			return nil
		},
	}

	cmd.Flags().Bool("all", false, "Process all sessions")
	cmd.Flags().Bool("unnamed-only", false, "Only rename sessions whose names match the auto-generated default pattern (login-hex or YYYY-MM-DD-word-word)")
	cmd.Flags().Int("limit", 0, "Cap the number of sessions processed (most-recent first)")
	cmd.Flags().Bool("dry-run", false, "Print generated names without saving")
	cmd.Flags().String("model", "haiku", "Claude model for name generation")
	return cmd
}

// generateName loads the session transcript and calls claude to produce a
// short kebab-case name. Returns an error if transcript is missing or LLM fails.
// homeDir and clotildeRootCache are unused but kept for future extension.
func generateName(
	_ interface{},
	sess *session.Session,
	_ string,
	_ map[string]string,
	model string,
) (string, error) {
	if sess.Metadata.TranscriptPath == "" {
		return "", fmt.Errorf("no transcript path")
	}
	if _, statErr := os.Stat(sess.Metadata.TranscriptPath); statErr != nil {
		return "", fmt.Errorf("transcript not found")
	}

	// Load up to 20 messages for naming context.
	f, err := os.Open(sess.Metadata.TranscriptPath)
	if err != nil {
		return "", fmt.Errorf("open transcript: %w", err)
	}
	messages, parseErr := transcript.Parse(f)
	_ = f.Close()
	if parseErr != nil {
		return "", fmt.Errorf("parse transcript: %w", parseErr)
	}
	if len(messages) == 0 {
		return "", fmt.Errorf("transcript has no messages")
	}

	// Take first 20 messages for context (intro sets the tone better than recent).
	sample := messages
	if len(sample) > 20 {
		sample = sample[:20]
	}

	var lines []string
	for _, msg := range sample {
		role := "User"
		if msg.Role == "assistant" {
			role = "Assistant"
		}
		text := msg.Text
		if len(text) > 300 {
			text = text[:300] + "..."
		}
		lines = append(lines, fmt.Sprintf("[%s] %s", role, text))
	}

	prompt := `You output exactly ONE token. That token is a kebab-case name with 3 to 5 words. All lowercase letters and hyphens only. No numbers. No periods. No quotes. No backticks. No spaces. No newlines. Do not greet. Do not explain. Do not ask questions. Do not write sentences. If you cannot determine a topic from the messages, output the literal string "unnamed-session". Never output more than 48 characters.

Good examples:
opnsense-bgp-cutover
clotilde-search-pipeline
tack-node-model-refactor
mwan-firewall-rules-cleanup

Messages:
` + strings.Join(lines, "\n")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	claudeCmd := exec.CommandContext(ctx, "claude", "-p", "--model", model, prompt)
	output, err := claudeCmd.Output()
	if err != nil {
		return "", fmt.Errorf("claude -p failed: %w", err)
	}

	// Parse the model output aggressively. The model sometimes returns a
	// paragraph despite the prompt; keep only the FIRST line and strip any
	// surrounding markup before validating.
	raw := strings.TrimSpace(string(output))
	if idx := strings.IndexAny(raw, "\r\n"); idx >= 0 {
		raw = raw[:idx]
	}
	// Remove common decoration: surrounding quotes, trailing punctuation,
	// leading list markers like "- " or "* ".
	raw = strings.Trim(raw, " \t`\"'"+".,;:!?)")
	raw = strings.TrimPrefix(raw, "- ")
	raw = strings.TrimPrefix(raw, "* ")
	raw = strings.TrimPrefix(raw, "> ")
	generated := strings.ToLower(raw)
	generated = strings.ReplaceAll(generated, " ", "-")
	// Reject outputs that look like prose. Anything above 48 chars, anything
	// with sentence punctuation, or anything with multi-line content is not
	// a name.
	if len(generated) > 48 ||
		strings.ContainsAny(generated, ".,!?\"'`()[]{}<>\n\r\t") {
		return "", fmt.Errorf("LLM returned prose, not a name (%d chars)", len(generated))
	}
	if generated == "unnamed-session" {
		return "", fmt.Errorf("LLM declined to name this session")
	}

	if !kebabRe.MatchString(generated) {
		return "", fmt.Errorf("LLM returned invalid name %q", generated)
	}

	return generated, nil
}
