// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: daemon.proto

package daemonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryEvent_Kind int32

const (
	RegistryEvent_KIND_UNSPECIFIED RegistryEvent_Kind = 0
	RegistryEvent_SESSION_ADOPTED  RegistryEvent_Kind = 1
	RegistryEvent_SESSION_UPDATED  RegistryEvent_Kind = 2
	RegistryEvent_SESSION_DELETED  RegistryEvent_Kind = 3
	RegistryEvent_SESSION_RENAMED  RegistryEvent_Kind = 4
	RegistryEvent_BRIDGE_OPENED    RegistryEvent_Kind = 5
	RegistryEvent_BRIDGE_CLOSED    RegistryEvent_Kind = 6
)

// Enum value maps for RegistryEvent_Kind.
var (
	RegistryEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "SESSION_ADOPTED",
		2: "SESSION_UPDATED",
		3: "SESSION_DELETED",
		4: "SESSION_RENAMED",
		5: "BRIDGE_OPENED",
		6: "BRIDGE_CLOSED",
	}
	RegistryEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"SESSION_ADOPTED":  1,
		"SESSION_UPDATED":  2,
		"SESSION_DELETED":  3,
		"SESSION_RENAMED":  4,
		"BRIDGE_OPENED":    5,
		"BRIDGE_CLOSED":    6,
	}
)

func (x RegistryEvent_Kind) Enum() *RegistryEvent_Kind {
	p := new(RegistryEvent_Kind)
	*p = x
	return p
}

func (x RegistryEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistryEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[0].Descriptor()
}

func (RegistryEvent_Kind) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[0]
}

func (x RegistryEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistryEvent_Kind.Descriptor instead.
func (RegistryEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12, 0}
}

type AcquireSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	WrapperId     string                 `protobuf:"bytes,2,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionRequest) Reset() {
	*x = AcquireSessionRequest{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionRequest) ProtoMessage() {}

func (x *AcquireSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionRequest.ProtoReflect.Descriptor instead.
func (*AcquireSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *AcquireSessionRequest) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

type AcquireSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FakeHome      string                 `protobuf:"bytes,1,opt,name=fake_home,json=fakeHome,proto3" json:"fake_home,omitempty"`
	RealClaude    string                 `protobuf:"bytes,2,opt,name=real_claude,json=realClaude,proto3" json:"real_claude,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SettingsFile  string                 `protobuf:"bytes,4,opt,name=settings_file,json=settingsFile,proto3" json:"settings_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionResponse) Reset() {
	*x = AcquireSessionResponse{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionResponse) ProtoMessage() {}

func (x *AcquireSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionResponse.ProtoReflect.Descriptor instead.
func (*AcquireSessionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireSessionResponse) GetFakeHome() string {
	if x != nil {
		return x.FakeHome
	}
	return ""
}

func (x *AcquireSessionResponse) GetRealClaude() string {
	if x != nil {
		return x.RealClaude
	}
	return ""
}

func (x *AcquireSessionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AcquireSessionResponse) GetSettingsFile() string {
	if x != nil {
		return x.SettingsFile
	}
	return ""
}

type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrapperId     string                 `protobuf:"bytes,1,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseSessionRequest) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

type ReleaseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionResponse) Reset() {
	*x = ReleaseSessionResponse{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionResponse) ProtoMessage() {}

func (x *ReleaseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

type HookEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	WrapperId     string                 `protobuf:"bytes,2,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	RawJson       []byte                 `protobuf:"bytes,3,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEventRequest) Reset() {
	*x = HookEventRequest{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEventRequest) ProtoMessage() {}

func (x *HookEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEventRequest.ProtoReflect.Descriptor instead.
func (*HookEventRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *HookEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookEventRequest) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

func (x *HookEventRequest) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type HookEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEventResponse) Reset() {
	*x = HookEventResponse{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEventResponse) ProtoMessage() {}

func (x *HookEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEventResponse.ProtoReflect.Descriptor instead.
func (*HookEventResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *HookEventResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ListActiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionsRequest) Reset() {
	*x = ListActiveSessionsRequest{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionsRequest) ProtoMessage() {}

func (x *ListActiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

type ListActiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ActiveSession       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionsResponse) Reset() {
	*x = ListActiveSessionsResponse{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionsResponse) ProtoMessage() {}

func (x *ListActiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *ListActiveSessionsResponse) GetSessions() []*ActiveSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ActiveSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	WrapperId     string                 `protobuf:"bytes,2,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSession) Reset() {
	*x = ActiveSession{}
	mi := &file_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSession) ProtoMessage() {}

func (x *ActiveSession) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSession.ProtoReflect.Descriptor instead.
func (*ActiveSession) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *ActiveSession) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ActiveSession) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

type TriggerScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScanRequest) Reset() {
	*x = TriggerScanRequest{}
	mi := &file_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScanRequest) ProtoMessage() {}

func (x *TriggerScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScanRequest.ProtoReflect.Descriptor instead.
func (*TriggerScanRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{9}
}

type TriggerScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdoptedCount  int32                  `protobuf:"varint,1,opt,name=adopted_count,json=adoptedCount,proto3" json:"adopted_count,omitempty"`
	AdoptedNames  []string               `protobuf:"bytes,2,rep,name=adopted_names,json=adoptedNames,proto3" json:"adopted_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScanResponse) Reset() {
	*x = TriggerScanResponse{}
	mi := &file_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScanResponse) ProtoMessage() {}

func (x *TriggerScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScanResponse.ProtoReflect.Descriptor instead.
func (*TriggerScanResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *TriggerScanResponse) GetAdoptedCount() int32 {
	if x != nil {
		return x.AdoptedCount
	}
	return 0
}

func (x *TriggerScanResponse) GetAdoptedNames() []string {
	if x != nil {
		return x.AdoptedNames
	}
	return nil
}

type SubscribeRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRegistryRequest) Reset() {
	*x = SubscribeRegistryRequest{}
	mi := &file_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRegistryRequest) ProtoMessage() {}

func (x *SubscribeRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRegistryRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRegistryRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{11}
}

type RegistryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            RegistryEvent_Kind     `protobuf:"varint,1,opt,name=kind,proto3,enum=agentgate.RegistryEvent_Kind" json:"kind,omitempty"`
	SessionName     string                 `protobuf:"bytes,2,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OldName         string                 `protobuf:"bytes,4,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	BridgeSessionId string                 `protobuf:"bytes,5,opt,name=bridge_session_id,json=bridgeSessionId,proto3" json:"bridge_session_id,omitempty"`
	BridgeUrl       string                 `protobuf:"bytes,6,opt,name=bridge_url,json=bridgeUrl,proto3" json:"bridge_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegistryEvent) Reset() {
	*x = RegistryEvent{}
	mi := &file_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEvent) ProtoMessage() {}

func (x *RegistryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEvent.ProtoReflect.Descriptor instead.
func (*RegistryEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *RegistryEvent) GetKind() RegistryEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return RegistryEvent_KIND_UNSPECIFIED
}

func (x *RegistryEvent) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *RegistryEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegistryEvent) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RegistryEvent) GetBridgeSessionId() string {
	if x != nil {
		return x.BridgeSessionId
	}
	return ""
}

func (x *RegistryEvent) GetBridgeUrl() string {
	if x != nil {
		return x.BridgeUrl
	}
	return ""
}

type RenameSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionRequest) Reset() {
	*x = RenameSessionRequest{}
	mi := &file_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionRequest) ProtoMessage() {}

func (x *RenameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *RenameSessionRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameSessionRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionResponse) Reset() {
	*x = RenameSessionResponse{}
	mi := &file_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionResponse) ProtoMessage() {}

func (x *RenameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionResponse.ProtoReflect.Descriptor instead.
func (*RenameSessionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{14}
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{16}
}

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	EffortLevel   string                 `protobuf:"bytes,2,opt,name=effort_level,json=effortLevel,proto3" json:"effort_level,omitempty"`
	OutputStyle   string                 `protobuf:"bytes,3,opt,name=output_style,json=outputStyle,proto3" json:"output_style,omitempty"`
	RemoteControl bool                   `protobuf:"varint,4,opt,name=remote_control,json=remoteControl,proto3" json:"remote_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *Settings) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Settings) GetEffortLevel() string {
	if x != nil {
		return x.EffortLevel
	}
	return ""
}

func (x *Settings) GetOutputStyle() string {
	if x != nil {
		return x.OutputStyle
	}
	return ""
}

func (x *Settings) GetRemoteControl() bool {
	if x != nil {
		return x.RemoteControl
	}
	return false
}

type UpdateSessionSettingsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Settings *Settings              `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	// Field names from Settings to apply. Empty mask means apply all
	// non zero fields. Listing remote_control alone toggles just that
	// value without overwriting model or anything else.
	UpdateMask    []string `protobuf:"bytes,3,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionSettingsRequest) Reset() {
	*x = UpdateSessionSettingsRequest{}
	mi := &file_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSettingsRequest) ProtoMessage() {}

func (x *UpdateSessionSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionSettingsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateSessionSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSessionSettingsRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateSessionSettingsRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateSessionSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionSettingsResponse) Reset() {
	*x = UpdateSessionSettingsResponse{}
	mi := &file_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSettingsResponse) ProtoMessage() {}

func (x *UpdateSessionSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionSettingsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{19}
}

type GlobalDefaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteControl bool                   `protobuf:"varint,1,opt,name=remote_control,json=remoteControl,proto3" json:"remote_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalDefaults) Reset() {
	*x = GlobalDefaults{}
	mi := &file_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalDefaults) ProtoMessage() {}

func (x *GlobalDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalDefaults.ProtoReflect.Descriptor instead.
func (*GlobalDefaults) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *GlobalDefaults) GetRemoteControl() bool {
	if x != nil {
		return x.RemoteControl
	}
	return false
}

type UpdateGlobalSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Defaults      *GlobalDefaults        `protobuf:"bytes,1,opt,name=defaults,proto3" json:"defaults,omitempty"`
	UpdateMask    []string               `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalSettingsRequest) Reset() {
	*x = UpdateGlobalSettingsRequest{}
	mi := &file_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalSettingsRequest) ProtoMessage() {}

func (x *UpdateGlobalSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalSettingsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateGlobalSettingsRequest) GetDefaults() *GlobalDefaults {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *UpdateGlobalSettingsRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateGlobalSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalSettingsResponse) Reset() {
	*x = UpdateGlobalSettingsResponse{}
	mi := &file_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalSettingsResponse) ProtoMessage() {}

func (x *UpdateGlobalSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateGlobalSettingsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{22}
}

type Bridge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid             int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	BridgeSessionId string                 `protobuf:"bytes,3,opt,name=bridge_session_id,json=bridgeSessionId,proto3" json:"bridge_session_id,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bridge) Reset() {
	*x = Bridge{}
	mi := &file_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bridge) ProtoMessage() {}

func (x *Bridge) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bridge.ProtoReflect.Descriptor instead.
func (*Bridge) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *Bridge) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Bridge) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Bridge) GetBridgeSessionId() string {
	if x != nil {
		return x.BridgeSessionId
	}
	return ""
}

func (x *Bridge) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListBridgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesRequest) Reset() {
	*x = ListBridgesRequest{}
	mi := &file_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesRequest) ProtoMessage() {}

func (x *ListBridgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesRequest.ProtoReflect.Descriptor instead.
func (*ListBridgesRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{24}
}

type ListBridgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*Bridge              `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesResponse) Reset() {
	*x = ListBridgesResponse{}
	mi := &file_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesResponse) ProtoMessage() {}

func (x *ListBridgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesResponse.ProtoReflect.Descriptor instead.
func (*ListBridgesResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *ListBridgesResponse) GetBridges() []*Bridge {
	if x != nil {
		return x.Bridges
	}
	return nil
}

type TailTranscriptRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// start_at_offset = 0 means stream future lines only.
	StartAtOffset int64 `protobuf:"varint,2,opt,name=start_at_offset,json=startAtOffset,proto3" json:"start_at_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailTranscriptRequest) Reset() {
	*x = TailTranscriptRequest{}
	mi := &file_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailTranscriptRequest) ProtoMessage() {}

func (x *TailTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailTranscriptRequest.ProtoReflect.Descriptor instead.
func (*TailTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *TailTranscriptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TailTranscriptRequest) GetStartAtOffset() int64 {
	if x != nil {
		return x.StartAtOffset
	}
	return 0
}

type TranscriptLine struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ByteOffset int64                  `protobuf:"varint,1,opt,name=byte_offset,json=byteOffset,proto3" json:"byte_offset,omitempty"`
	RawJsonl   string                 `protobuf:"bytes,2,opt,name=raw_jsonl,json=rawJsonl,proto3" json:"raw_jsonl,omitempty"`
	Role       string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Text       string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Unix nanoseconds. Avoids pulling in google.protobuf.Timestamp for one field.
	TimestampNanos int64 `protobuf:"varint,5,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranscriptLine) Reset() {
	*x = TranscriptLine{}
	mi := &file_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptLine) ProtoMessage() {}

func (x *TranscriptLine) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptLine.ProtoReflect.Descriptor instead.
func (*TranscriptLine) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *TranscriptLine) GetByteOffset() int64 {
	if x != nil {
		return x.ByteOffset
	}
	return 0
}

func (x *TranscriptLine) GetRawJsonl() string {
	if x != nil {
		return x.RawJsonl
	}
	return ""
}

func (x *TranscriptLine) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TranscriptLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptLine) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

type SendToSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToSessionRequest) Reset() {
	*x = SendToSessionRequest{}
	mi := &file_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToSessionRequest) ProtoMessage() {}

func (x *SendToSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToSessionRequest.ProtoReflect.Descriptor instead.
func (*SendToSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *SendToSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendToSessionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendToSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int32                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Delivered     bool                   `protobuf:"varint,2,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToSessionResponse) Reset() {
	*x = SendToSessionResponse{}
	mi := &file_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToSessionResponse) ProtoMessage() {}

func (x *SendToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToSessionResponse.ProtoReflect.Descriptor instead.
func (*SendToSessionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{29}
}

func (x *SendToSessionResponse) GetBytesWritten() int32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *SendToSessionResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\tagentgate\"Y\n" +
	"\x15AcquireSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x02 \x01(\tR\twrapperId\"\x91\x01\n" +
	"\x16AcquireSessionResponse\x12\x1b\n" +
	"\tfake_home\x18\x01 \x01(\tR\bfakeHome\x12\x1f\n" +
	"\vreal_claude\x18\x02 \x01(\tR\n" +
	"realClaude\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rsettings_file\x18\x04 \x01(\tR\fsettingsFile\"6\n" +
	"\x15ReleaseSessionRequest\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x01 \x01(\tR\twrapperId\"\x18\n" +
	"\x16ReleaseSessionResponse\"f\n" +
	"\x10HookEventRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x02 \x01(\tR\twrapperId\x12\x19\n" +
	"\braw_json\x18\x03 \x01(\fR\arawJson\"0\n" +
	"\x11HookEventResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"\x1b\n" +
	"\x19ListActiveSessionsRequest\"R\n" +
	"\x1aListActiveSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.agentgate.ActiveSessionR\bsessions\"Q\n" +
	"\rActiveSession\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x02 \x01(\tR\twrapperId\"\x14\n" +
	"\x12TriggerScanRequest\"_\n" +
	"\x13TriggerScanResponse\x12#\n" +
	"\radopted_count\x18\x01 \x01(\x05R\fadoptedCount\x12#\n" +
	"\radopted_names\x18\x02 \x03(\tR\fadoptedNames\"\x1a\n" +
	"\x18SubscribeRegistryRequest\"\x83\x03\n" +
	"\rRegistryEvent\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.agentgate.RegistryEvent.KindR\x04kind\x12!\n" +
	"\fsession_name\x18\x02 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\bold_name\x18\x04 \x01(\tR\aoldName\x12*\n" +
	"\x11bridge_session_id\x18\x05 \x01(\tR\x0fbridgeSessionId\x12\x1d\n" +
	"\n" +
	"bridge_url\x18\x06 \x01(\tR\tbridgeUrl\"\x96\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSESSION_ADOPTED\x10\x01\x12\x13\n" +
	"\x0fSESSION_UPDATED\x10\x02\x12\x13\n" +
	"\x0fSESSION_DELETED\x10\x03\x12\x13\n" +
	"\x0fSESSION_RENAMED\x10\x04\x12\x11\n" +
	"\rBRIDGE_OPENED\x10\x05\x12\x11\n" +
	"\rBRIDGE_CLOSED\x10\x06\"L\n" +
	"\x14RenameSessionRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"\x17\n" +
	"\x15RenameSessionResponse\"*\n" +
	"\x14DeleteSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15DeleteSessionResponse\"\x8d\x01\n" +
	"\bSettings\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\feffort_level\x18\x02 \x01(\tR\veffortLevel\x12!\n" +
	"\foutput_style\x18\x03 \x01(\tR\voutputStyle\x12%\n" +
	"\x0eremote_control\x18\x04 \x01(\bR\rremoteControl\"\x84\x01\n" +
	"\x1cUpdateSessionSettingsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\bsettings\x18\x02 \x01(\v2\x13.agentgate.SettingsR\bsettings\x12\x1f\n" +
	"\vupdate_mask\x18\x03 \x03(\tR\n" +
	"updateMask\"\x1f\n" +
	"\x1dUpdateSessionSettingsResponse\"7\n" +
	"\x0eGlobalDefaults\x12%\n" +
	"\x0eremote_control\x18\x01 \x01(\bR\rremoteControl\"u\n" +
	"\x1bUpdateGlobalSettingsRequest\x125\n" +
	"\bdefaults\x18\x01 \x01(\v2\x19.agentgate.GlobalDefaultsR\bdefaults\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x03(\tR\n" +
	"updateMask\"\x1e\n" +
	"\x1cUpdateGlobalSettingsResponse\"w\n" +
	"\x06Bridge\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12*\n" +
	"\x11bridge_session_id\x18\x03 \x01(\tR\x0fbridgeSessionId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\x14\n" +
	"\x12ListBridgesRequest\"B\n" +
	"\x13ListBridgesResponse\x12+\n" +
	"\abridges\x18\x01 \x03(\v2\x11.agentgate.BridgeR\abridges\"^\n" +
	"\x15TailTranscriptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\x0fstart_at_offset\x18\x02 \x01(\x03R\rstartAtOffset\"\x9f\x01\n" +
	"\x0eTranscriptLine\x12\x1f\n" +
	"\vbyte_offset\x18\x01 \x01(\x03R\n" +
	"byteOffset\x12\x1b\n" +
	"\traw_jsonl\x18\x02 \x01(\tR\brawJsonl\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12'\n" +
	"\x0ftimestamp_nanos\x18\x05 \x01(\x03R\x0etimestampNanos\"I\n" +
	"\x14SendToSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"Z\n" +
	"\x15SendToSessionResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x05R\fbytesWritten\x12\x1c\n" +
	"\tdelivered\x18\x02 \x01(\bR\tdelivered2\xf9\b\n" +
	"\n" +
	"AgentGateD\x12U\n" +
	"\x0eAcquireSession\x12 .agentgate.AcquireSessionRequest\x1a!.agentgate.AcquireSessionResponse\x12U\n" +
	"\x0eReleaseSession\x12 .agentgate.ReleaseSessionRequest\x1a!.agentgate.ReleaseSessionResponse\x12F\n" +
	"\tHookEvent\x12\x1b.agentgate.HookEventRequest\x1a\x1c.agentgate.HookEventResponse\x12a\n" +
	"\x12ListActiveSessions\x12$.agentgate.ListActiveSessionsRequest\x1a%.agentgate.ListActiveSessionsResponse\x12L\n" +
	"\vTriggerScan\x12\x1d.agentgate.TriggerScanRequest\x1a\x1e.agentgate.TriggerScanResponse\x12T\n" +
	"\x11SubscribeRegistry\x12#.agentgate.SubscribeRegistryRequest\x1a\x18.agentgate.RegistryEvent0\x01\x12R\n" +
	"\rRenameSession\x12\x1f.agentgate.RenameSessionRequest\x1a .agentgate.RenameSessionResponse\x12R\n" +
	"\rDeleteSession\x12\x1f.agentgate.DeleteSessionRequest\x1a .agentgate.DeleteSessionResponse\x12j\n" +
	"\x15UpdateSessionSettings\x12'.agentgate.UpdateSessionSettingsRequest\x1a(.agentgate.UpdateSessionSettingsResponse\x12g\n" +
	"\x14UpdateGlobalSettings\x12&.agentgate.UpdateGlobalSettingsRequest\x1a'.agentgate.UpdateGlobalSettingsResponse\x12L\n" +
	"\vListBridges\x12\x1d.agentgate.ListBridgesRequest\x1a\x1e.agentgate.ListBridgesResponse\x12O\n" +
	"\x0eTailTranscript\x12 .agentgate.TailTranscriptRequest\x1a\x19.agentgate.TranscriptLine0\x01\x12R\n" +
	"\rSendToSession\x12\x1f.agentgate.SendToSessionRequest\x1a .agentgate.SendToSessionResponseB)Z'github.com/fgrehm/clotilde/api/daemonpbb\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_daemon_proto_goTypes = []any{
	(RegistryEvent_Kind)(0),               // 0: agentgate.RegistryEvent.Kind
	(*AcquireSessionRequest)(nil),         // 1: agentgate.AcquireSessionRequest
	(*AcquireSessionResponse)(nil),        // 2: agentgate.AcquireSessionResponse
	(*ReleaseSessionRequest)(nil),         // 3: agentgate.ReleaseSessionRequest
	(*ReleaseSessionResponse)(nil),        // 4: agentgate.ReleaseSessionResponse
	(*HookEventRequest)(nil),              // 5: agentgate.HookEventRequest
	(*HookEventResponse)(nil),             // 6: agentgate.HookEventResponse
	(*ListActiveSessionsRequest)(nil),     // 7: agentgate.ListActiveSessionsRequest
	(*ListActiveSessionsResponse)(nil),    // 8: agentgate.ListActiveSessionsResponse
	(*ActiveSession)(nil),                 // 9: agentgate.ActiveSession
	(*TriggerScanRequest)(nil),            // 10: agentgate.TriggerScanRequest
	(*TriggerScanResponse)(nil),           // 11: agentgate.TriggerScanResponse
	(*SubscribeRegistryRequest)(nil),      // 12: agentgate.SubscribeRegistryRequest
	(*RegistryEvent)(nil),                 // 13: agentgate.RegistryEvent
	(*RenameSessionRequest)(nil),          // 14: agentgate.RenameSessionRequest
	(*RenameSessionResponse)(nil),         // 15: agentgate.RenameSessionResponse
	(*DeleteSessionRequest)(nil),          // 16: agentgate.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),         // 17: agentgate.DeleteSessionResponse
	(*Settings)(nil),                      // 18: agentgate.Settings
	(*UpdateSessionSettingsRequest)(nil),  // 19: agentgate.UpdateSessionSettingsRequest
	(*UpdateSessionSettingsResponse)(nil), // 20: agentgate.UpdateSessionSettingsResponse
	(*GlobalDefaults)(nil),                // 21: agentgate.GlobalDefaults
	(*UpdateGlobalSettingsRequest)(nil),   // 22: agentgate.UpdateGlobalSettingsRequest
	(*UpdateGlobalSettingsResponse)(nil),  // 23: agentgate.UpdateGlobalSettingsResponse
	(*Bridge)(nil),                        // 24: agentgate.Bridge
	(*ListBridgesRequest)(nil),            // 25: agentgate.ListBridgesRequest
	(*ListBridgesResponse)(nil),           // 26: agentgate.ListBridgesResponse
	(*TailTranscriptRequest)(nil),         // 27: agentgate.TailTranscriptRequest
	(*TranscriptLine)(nil),                // 28: agentgate.TranscriptLine
	(*SendToSessionRequest)(nil),          // 29: agentgate.SendToSessionRequest
	(*SendToSessionResponse)(nil),         // 30: agentgate.SendToSessionResponse
}
var file_daemon_proto_depIdxs = []int32{
	9,  // 0: agentgate.ListActiveSessionsResponse.sessions:type_name -> agentgate.ActiveSession
	0,  // 1: agentgate.RegistryEvent.kind:type_name -> agentgate.RegistryEvent.Kind
	18, // 2: agentgate.UpdateSessionSettingsRequest.settings:type_name -> agentgate.Settings
	21, // 3: agentgate.UpdateGlobalSettingsRequest.defaults:type_name -> agentgate.GlobalDefaults
	24, // 4: agentgate.ListBridgesResponse.bridges:type_name -> agentgate.Bridge
	1,  // 5: agentgate.AgentGateD.AcquireSession:input_type -> agentgate.AcquireSessionRequest
	3,  // 6: agentgate.AgentGateD.ReleaseSession:input_type -> agentgate.ReleaseSessionRequest
	5,  // 7: agentgate.AgentGateD.HookEvent:input_type -> agentgate.HookEventRequest
	7,  // 8: agentgate.AgentGateD.ListActiveSessions:input_type -> agentgate.ListActiveSessionsRequest
	10, // 9: agentgate.AgentGateD.TriggerScan:input_type -> agentgate.TriggerScanRequest
	12, // 10: agentgate.AgentGateD.SubscribeRegistry:input_type -> agentgate.SubscribeRegistryRequest
	14, // 11: agentgate.AgentGateD.RenameSession:input_type -> agentgate.RenameSessionRequest
	16, // 12: agentgate.AgentGateD.DeleteSession:input_type -> agentgate.DeleteSessionRequest
	19, // 13: agentgate.AgentGateD.UpdateSessionSettings:input_type -> agentgate.UpdateSessionSettingsRequest
	22, // 14: agentgate.AgentGateD.UpdateGlobalSettings:input_type -> agentgate.UpdateGlobalSettingsRequest
	25, // 15: agentgate.AgentGateD.ListBridges:input_type -> agentgate.ListBridgesRequest
	27, // 16: agentgate.AgentGateD.TailTranscript:input_type -> agentgate.TailTranscriptRequest
	29, // 17: agentgate.AgentGateD.SendToSession:input_type -> agentgate.SendToSessionRequest
	2,  // 18: agentgate.AgentGateD.AcquireSession:output_type -> agentgate.AcquireSessionResponse
	4,  // 19: agentgate.AgentGateD.ReleaseSession:output_type -> agentgate.ReleaseSessionResponse
	6,  // 20: agentgate.AgentGateD.HookEvent:output_type -> agentgate.HookEventResponse
	8,  // 21: agentgate.AgentGateD.ListActiveSessions:output_type -> agentgate.ListActiveSessionsResponse
	11, // 22: agentgate.AgentGateD.TriggerScan:output_type -> agentgate.TriggerScanResponse
	13, // 23: agentgate.AgentGateD.SubscribeRegistry:output_type -> agentgate.RegistryEvent
	15, // 24: agentgate.AgentGateD.RenameSession:output_type -> agentgate.RenameSessionResponse
	17, // 25: agentgate.AgentGateD.DeleteSession:output_type -> agentgate.DeleteSessionResponse
	20, // 26: agentgate.AgentGateD.UpdateSessionSettings:output_type -> agentgate.UpdateSessionSettingsResponse
	23, // 27: agentgate.AgentGateD.UpdateGlobalSettings:output_type -> agentgate.UpdateGlobalSettingsResponse
	26, // 28: agentgate.AgentGateD.ListBridges:output_type -> agentgate.ListBridgesResponse
	28, // 29: agentgate.AgentGateD.TailTranscript:output_type -> agentgate.TranscriptLine
	30, // 30: agentgate.AgentGateD.SendToSession:output_type -> agentgate.SendToSessionResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
